name: walisongo_app
description: "A new Flutter project."
flutter:
  assets:
    - assets/images/menara_kudus.jpg.jpeg
    - assets/images/masjid_demak.jpg.jpeg
    - assets/images/makam_wali.jpg.jpeg